https://bowfinger.de/blog/tag/python/
https://jsdokken.com/src/tutorial_gmsh.html
https://www.geeksforgeeks.org/how-to-generate-mesh-in-python-with-gmsh-module/
https://keurfonluu.github.io/toughio/examples/co2_leakage_along_a_fault/1_generate_mesh_in_python_with_gmsh.html
https://fenicsproject.org/olddocs/dolfinx/dev/python/demos/gmsh/demo_gmsh.py.html
https://gitlab.onelab.info/gmsh/gmsh/blob/master/tutorials/python/t1.py
https://gitlab.onelab.info/gmsh/gmsh/blob/gmsh_4_8_3/tutorial/python/t3.py
https://gitlab.onelab.info/gmsh/gmsh/-/tree/gmsh_4_8_3/tutorial/python
https://www.opengeosys.org/docs/tools/getting-started/video-tutorial/mesh_basin.py
https://gmsh.info/doc/texinfo/gmsh.html
https://gmsh.info/doc/texinfo/gmsh.html#Choosing-the-right-unstructured-algorithm
https://docs.pyvista.org/api/core/_autosummary/pyvista.DataSet.compute_cell_quality.html
https://docs.pyvista.org/examples/01-filter/mesh-quality.html#mesh-quality-example
https://docs.pyvista.org/examples/02-plot/screenshot.html
https://docs.pyvista.org/examples/03-widgets/slider-bar-widget.html
https://docs.pyvista.org/api/plotting/_autosummary/pyvista.Plotter.add_mesh_clip_box.html
https://www.pygimli.org/_examples_auto/1_meshing/plot_gmsh-example.html
https://www.pygimli.org/_examples_auto/index.html
https://gitlab.onelab.info/gmsh/gmsh/-/blob/master/tutorials/c%2B%2B/t11.cpp
https://pdfs.semanticscholar.org/9989/bfd3f21c1dd108508b4d1edb1dbdf00d89f7.pdf
file://ccfepc/Home/P-T/rg5749/Downloads/gmsh.pdf
https://swcarpentry.github.io/shell-novice/setup.html
https://pythonhosted.org/planar/polygon.html
https://pythonhosted.org/planar/index.html
https://www.folkstalk.com/tech/python-find-center-of-polygon-function-with-code-examples/
https://www.toptal.com/python/computational-geometry-in-python-from-theory-to-implementation
https://github.com/greenm01/poly2tri
https://csveda.com/python-line-circle-and-polygon-functions/
https://pyimagesearch.com/2016/03/21/ordering-coordinates-clockwise-with-python-and-opencv/
https://kannadakali.org/learning/curriculum/curriculum.html
https://archive.org/details/DLIKannadaKavanaSankalana/Cheluvu%20-%20Maasti%20Venkatesh%20Ayyangar/page/n13/mode/2up?view=theater
https://archive.org/details/DLIKannadaKavanaSankalana/Kindari%20Jogi%20-%20Kuvempu/page/n3/mode/2up?view=theater
https://archive.org/details/DLIKannadaKavanaSankalana/naadaleele%20-%20Da%20Ra%20Bendre/page/n19/mode/2up?view=theater
https://archive.org/details/DLIKannadaKavanaSankalana/Uyyaale%20-%20Da%20Ra%20Bendre/page/n27/mode/2up
https://archive.org/details/DLIKannadaKavanaSankalana/naadaleele%20-%20Da%20Ra%20Bendre/page/n35/mode/2up
https://stackoverflow.com/questions/16750618/whats-an-efficient-way-to-find-if-a-point-lies-in-the-convex-hull-of-a-point-cl
https://stackoverflow.com/questions/10650645/python-calculate-voronoi-tesselation-from-scipys-delaunay-triangulation-in-3d
http://www.gdmc.nl/publications/2009/3D_Voronoi_diagram.pdf
https://github.com/joe-jordan/pyvoro
file://ccfepc/Home/P-T/rg5749/Downloads/539221942-MIT.pdf
http://web.mit.edu/calculix_v2.7/CalculiX/ccx_2.7/doc/ccx/node278.html
https://www.brown.edu/Departments/Engineering/Courses/En2340/Programming/ABAQUS/Usermat.for
https://imechanica.org/files/Writing%20a%20UMAT.pdf
https://simplifiedfem.wordpress.com/about/tutorial-write-a-simple-umat-in-abaqus/
http://web.mit.edu/course/3/3.11/www/modules/airy.pdf
http://esag.harvard.edu/rice/018_Rice_MathAnalMechFract_68.pdf
https://www.researcher-app.com/paper/13173518?utm_source=newsletter&utm_medium=email&utm_campaign=live_newsletter
https://www.oxinst.com/blogs/why-precision-matters-for-electron-backscatter-diffraction?business=nanoanalysis&sbms=nanoanalysis&utm_source=GM&utm_medium=email&utm_campaign=2022+-+Global+-+Email+-+Newsletter%3A+November&utm_term=News+just+in%3A+November+2022&utm_content=11376&gator_td=5VyqBkQYIxe790mlDVk6cdRTQ7KO0FP7uS%2BTa2CB4wx%2F59p4GUe72KnYwAjj0qxQFhkjnFXRbntmdJqPC6R6T6rfcm93rha7qZSPtA96NDSYx31Zwii8FMXa%2BMLWvl3JpkuTlhm%2FWY8MVsa%2BtTl79bREtKAh8D5ia23hjMeFEDWXGSHSysVTRXwgX1wZgJQs7Cq1WwdN0BrX23whiq%2F%2Fsg%3D%3D
https://www.oxinst.com/blogs/analysis-of-non-metallic-inclusions-in-steels-with-aztecsteel?business=nanoanalysis&sbms=nanoanalysis&utm_source=GM&utm_medium=email&utm_campaign=2022+-+Global+-+Email+-+Newsletter%3A+November&utm_term=News+just+in%3A+November+2022&utm_content=11376&gator_td=5VyqBkQYIxe790mlDVk6cdRTQ7KO0FP7uS%2BTa2CB4wx%2F59p4GUe72KnYwAjj0qxQFhkjnFXRbntmdJqPC6R6T6rfcm93rha7qZSPtA96NDSYx31Zwii8FMXa%2BMLWvl3JpkuTlhm%2FWY8MVsa%2BtTl79bREtKAh8D5ia23hjMeFEDWXGSHSysVTRXwgX1wZgJQs7Cq1WwdN0BrX23whiq%2F%2Fsg%3D%3D
https://archive.org/details/DLIKannadaKavanaSankalana/Kindari%20Jogi%20-%20Kuvempu/page/n11/mode/2up?view=theater
https://janapada.karnataka.gov.in/storage/pdf-files/academy%20books/%E0%B2%9C%E0%B2%BE%E0%B2%A8%E0%B2%AA%E0%B2%A6%20%E0%B2%A4%E0%B2%B2%E0%B3%86%E0%B2%AE%E0%B2%BE%E0%B2%B0%E0%B3%81%20%E0%B2%AD%E0%B2%BE%E0%B2%97%201.pdf
https://archive.org/details/in.ernet.dli.2015.363816
https://archive.org/details/janapada_geete/page/n1/mode/2up
https://archive.org/details/dli.osmania.4981/page/n55/mode/2up?view=theater
https://www.temple.org/templates/jd_boston/downloads/kids_sloka.pdf
https://sanskritdocuments.org/sanskrit/shloka/
https://sanskritdocuments.org/doc_z_misc_general/DAILY_PRAYERS04.pdf
https://sanskritdocuments.org/doc_z_misc_general/Shlokabook1-formatted.PDF
https://sanskritdocuments.org/doc_z_misc_general/shloka3.pdf
https://sanskritdocuments.org/doc_z_misc_general/shloka1.html
https://sanskritdocuments.org/doc_z_misc_general/shloka2.html
https://sanskritdocuments.org/doc_z_misc_general/prayers.pdf
https://sanskritdocuments.org/doc_z_misc_general/Shlokabook1-formatted.PDF
https://pypi.org/project/pyvoro/
https://docs.microstructpy.org/en/latest/examples/index.html#python-package-examples
https://arxiv.org/pdf/2107.02460.pdf
https://docs.scipy.org/doc/scipy/reference/optimize.html
https://shapely.readthedocs.io/en/stable/manual.html
https://tex.stackexchange.com/questions/276647/change-pgfplots-markers-colors-and-shape
https://www.atlantakannada.org/kannada-kali
https://kannadapraadhikaara.karnataka.gov.in/info-4/KDA/kn
https://www.atlantakannada.org/sign-up-forms
https://www.austinkannadasangha.org/kannada-kali
https://www.bakannadakali.org/
https://sanskritdocuments.org/sanskrit/veda/
https://sanskritdocuments.org/doc_veda/svastisUktam.pdf
https://shapely.readthedocs.io/en/latest/strtree.html
https://shapely.readthedocs.io/en/latest/manual.html#spatial-analysis-methods
https://github.com/shapely/shapely
https://shapely.readthedocs.io/en/latest/properties.html
https://www.youtube.com/watch?v=4hcXa8aGu_c
https://www.youtube.com/watch?v=A7bBMcVZWSM
https://archive.org/details/samskruta-sarala-vyakarana/page/29/mode/2up?view=theater
